# Generated by Django 5.1.1 on 2024-09-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_alter_user_category_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
